/**
 * Seed Script — Populates MongoDB with destinations and hotels
 * Run: node src/seed.js
 */
const mongoose = require("mongoose");
const dotenv = require("dotenv");

dotenv.config();

const Destination = require("./models/Destination");
const Hotel = require("./models/Hotel");

const destinations = [
  // ── ISLAMABAD ──
  { name: "Faisal Mosque", city: "Islamabad", category: "Religious", rating: 4.9, price: 0, badge: "Iconic", description: "An iconic white marble mosque featuring contemporary Islamic architecture. Designed by Turkish architect Vedat Dalokay, it can accommodate up to 100,000 worshippers.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuyE7LQ_-1ykXHSQAqb8CJZA2CBr6JV31R1Q&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuyE7LQ_-1ykXHSQAqb8CJZA2CBr6JV31R1Q&s", openingHours: "5:00 AM – 11:00 PM", bestTime: "Sunset", duration: "1.5-2 hours", highlights: [{ icon: "🕌", title: "Architectural Marvel", subtitle: "Modern Bedouin-tent design" }, { icon: "📷", title: "Photo Spot", subtitle: "Stunning Margalla Hills backdrop" }, { icon: "🌅", title: "Sunset Views", subtitle: "Best visited in golden hour" }, { icon: "🎓", title: "Islamic University", subtitle: "Houses IIUI campus nearby" }], tips: ["Dress modestly — cover shoulders and knees. Women must cover their heads.", "Best time: early morning or just before sunset.", "Free parking available on-site. Allow 1.5–2 hours."] },
  { name: "Daman-e-Koh", city: "Islamabad", category: "Nature", rating: 4.7, price: 50, badge: "Viewpoint", description: "A hilltop garden offering panoramic views of the capital city and surrounding Margalla Hills.", image: "https://propakistani.pk/wp-content/uploads/2021/08/Daman-e-Koh-1.jpg", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8MTrBE43gcy5uuvWYD-Ic0ukOscdzcNfUgg&s", bestTime: "Evening", duration: "1-2 hours" },
  { name: "Pakistan Monument", city: "Islamabad", category: "Landmark", rating: 4.8, price: 100, badge: "Heritage", description: "A bronze lotus petal monument symbolizing the country's diverse cultures and provinces.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlLt1uuoCpm9Pqpk6QE3UURQnmBS0bdM5bng&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwfmfnVagLjVxXHDtGZ7UQAgD2h2wG8OdcoA&s", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Margalla Hills", city: "Islamabad", category: "Nature", rating: 4.9, price: 0, badge: "Trails", description: "Green hills harboring popular hiking trails and dense forests at the foothills of the Himalayas.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf8i6clZ_huHdD_zqs2GxOehWSX7MRgf4SUA&s", detailImage: "https://propakistani.pk/proproperty/wp-content/uploads/2023/10/Margalla-Hills-National-Park.jpg", bestTime: "Morning", duration: "3-4 hours" },
  { name: "Lok Virsa Museum", city: "Islamabad", category: "Culture", rating: 4.6, price: 200, badge: "Museum", description: "A cultural museum preserving the rich heritage and traditions of Pakistan's diverse regions.", image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80", bestTime: "Afternoon", duration: "2-3 hours" },
  { name: "Centaurus Mall", city: "Islamabad", category: "Shopping", rating: 4.5, price: 0, badge: "Modern", description: "A modern, multi-story shopping mall with premium brands, food courts, and entertainment.", image: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&q=80", bestTime: "Evening", duration: "2-3 hours" },
  { name: "Khanpur Dam", city: "Haripur", category: "Nature", rating: 4.6, price: 200, badge: "Lake", description: "A scenic reservoir on the Haro River, popular for water sports, boating, and picnics near Islamabad.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7srzp_V3Q5CipmKZaPbGVOX2wjCSHp-3Zqw&s", detailImage: "https://cdn-blog.zameen.com/blog/wp-content/uploads/2020/07/coverkhanpur1.jpg", bestTime: "Morning", duration: "Half day" },
  { name: "Taxila", city: "Rawalpindi", category: "Historic", rating: 4.7, price: 200, badge: "UNESCO", description: "One of the most important archaeological sites in Asia, Taxila was a major centre of Gandhara culture and Buddhist learning.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1Uh-s8CelRAn3Th16pyaX_2lqPAvzFuShrg&s", detailImage: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/fa/2c/d8/taxila.jpg?w=1200&h=-1&s=1", bestTime: "Morning", duration: "3-4 hours" },

  // ── LAHORE ──
  { name: "Badshahi Mosque", city: "Lahore", category: "Religious", rating: 4.9, price: 50, badge: "Grand", description: "A massive, beautifully crafted Mughal-era mosque and one of the largest in the world.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt2qYaFu9u0FYOQq0Fl75Z0VqD56wvB2KzqQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt2qYaFu9u0FYOQq0Fl75Z0VqD56wvB2KzqQ&s", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Lahore Fort", city: "Lahore", category: "Historic", rating: 4.8, price: 100, badge: "UNESCO", description: "A historical fort complex reflecting royal Mughal architecture spanning centuries of history.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyHCMy83EbG4H0xbMkmoPlmT6pePI09nDdhQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyHCMy83EbG4H0xbMkmoPlmT6pePI09nDdhQ&s", bestTime: "Morning", duration: "2-3 hours" },
  { name: "Shalimar Gardens", city: "Lahore", category: "Nature", rating: 4.5, price: 50, badge: "Scenic", description: "Terraced Mughal gardens built as a royal paradise of water features and lush flora.", image: "https://images.unsplash.com/photo-1585325701165-f1f97d41bb6b?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1585325701165-f1f97d41bb6b?w=800&q=80", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Walled City Lahore", city: "Lahore", category: "Culture", rating: 4.7, price: 0, badge: "Bazaars", description: "The bustling historic heart of the city full of lively bazaars and narrow streets.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpMCxh8LulglgU8L94ZaUazMgC-njltDF8Qg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0J3kM1lym80Ge6tDj4qqs69DLPp585tYkaw&s", bestTime: "Evening", duration: "3-4 hours" },
  { name: "Wagah Border", city: "Lahore", category: "Landmark", rating: 4.8, price: 0, badge: "Patriotic", description: "Famous for the daily, energetic flag-lowering military ceremony at the Pakistan-India border.", image: "https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2023/01/24155424/Wagah-Border-1-1.jpg?tr=w-1200,q-60", detailImage: "https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2023/01/24155424/Wagah-Border-1-1.jpg?tr=w-1200,q-60", bestTime: "Evening", duration: "2-3 hours" },
  { name: "Food Street Lahore", city: "Lahore", category: "Food", rating: 4.9, price: 1500, badge: "Culinary", description: "A lively culinary hub serving authentic traditional Lahori delicacies and street food.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROq1txhcuCRJhEWM7Pc5KnMlMC47r_-_u4sg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTduJN7iak-QyNh05bQXd-0u3B-fzco6OjPEA&s", bestTime: "Evening", duration: "2-3 hours" },
  { name: "Wazir Khan Mosque", city: "Lahore", category: "Religious", rating: 4.8, price: 0, badge: "Mughal", description: "A 17th-century Mughal mosque renowned for its elaborate faience tile work and intricate frescoes, located in the Walled City.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxrVYnVQip3E9As8dwcHEcgxL3u_CL1fGidg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxrVYnVQip3E9As8dwcHEcgxL3u_CL1fGidg&s", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Gawalmandi", city: "Lahore", category: "Food", rating: 4.7, price: 500, badge: "Street Food", description: "Lahore's most famous food bazaar offering an unmatched spread of traditional Punjabi street food and local delicacies.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtTyqNJjhpi9hJGie6XilU-aswf94DNE8i1A&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtl0dAJ9y-wW1prl62zAXRZy75mgA3v9cXXg&s", bestTime: "Evening", duration: "2-3 hours" },
  { name: "Rohtas Fort", city: "Jhelum", category: "Historic", rating: 4.6, price: 100, badge: "UNESCO", description: "A 16th-century fortification built by Sher Shah Suri, recognized as a UNESCO World Heritage Site for its massive ramparts and gateways.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUpS_qfll-ZZkvo8aL2xmaFPidy3DRv7brMA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXH5UNbtw0y38WbGlHBU3WhaOvfappuxOtng&s", bestTime: "Morning", duration: "2-3 hours" },

  // ── KARACHI ──
  { name: "Clifton Beach", city: "Karachi", category: "Beach", rating: 4.4, price: 0, badge: "Relax", description: "A popular city beach along the Arabian Sea coast, perfect for evening strolls.", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", bestTime: "Evening", duration: "2-3 hours" },
  { name: "Quaid Mausoleum", city: "Karachi", category: "Historic", rating: 4.7, price: 50, badge: "Mazar", description: "The serene white marble resting place of Pakistan's founder, Quaid-e-Azam Muhammad Ali Jinnah.", image: "https://stdc.gos.pk/wp-content/uploads/2024/10/Mazar-e-Quaid-Canvas-16x20-1-scaled.jpg", detailImage: "https://chakorventures.com/wp-content/uploads/2025/10/mazar-e-quaid-exterior-view.jpg", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Mohatta Palace", city: "Karachi", category: "Culture", rating: 4.6, price: 150, badge: "Museum", description: "A grand, intricately designed palace serving as an art and heritage museum.", image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80", bestTime: "Afternoon", duration: "1-2 hours" },
  { name: "Port Grand", city: "Karachi", category: "Food", rating: 4.5, price: 500, badge: "Dining", description: "A scenic waterfront complex full of diverse food stands, restaurants, and entertainment.", image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", bestTime: "Evening", duration: "2-3 hours" },
  { name: "Empress Market", city: "Karachi", category: "Shopping", rating: 4.3, price: 0, badge: "Bazaar", description: "A historic, colonial-era market bustling with fresh goods, spices, and local crafts.", image: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&q=80", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Manora Island", city: "Karachi", category: "Nature", rating: 4.2, price: 200, badge: "Island", description: "A small, peaceful island accessible by boat featuring a tall lighthouse and beaches.", image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80", bestTime: "Morning", duration: "Half day" },

  // ── HUNZA ──
  { name: "Rakaposhi Basecamp", city: "Hunza", category: "Adventure", rating: 4.9, price: 0, badge: "Vista", description: "A breathtaking viewpoint and trekking destination with direct views of the 7,788m Rakaposhi peak rising above the valley.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9eW4WtcQSOhW1heX1EdmU1lYymK_voC-AzA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9eW4WtcQSOhW1heX1EdmU1lYymK_voC-AzA&s", bestTime: "Morning", duration: "30 min", isHiddenGem: true },
  { name: "Attabad Lake", city: "Hunza", category: "Nature", rating: 5.0, price: 300, badge: "Lake", description: "A stunning turquoise blue lake formed after a 2010 landslide, perfect for boating, jetskiing, and photography.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_vWdMW2aY1XWuzjaj5jGaUCFQ9CWRY8zsoA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_vWdMW2aY1XWuzjaj5jGaUCFQ9CWRY8zsoA&s", bestTime: "Morning", duration: "2-3 hours" },
  { name: "Baltit Fort", city: "Hunza", category: "Historic", rating: 4.8, price: 500, badge: "Ancient", description: "An ancient fort perched high above Karimabad offering sweeping views of the Hunza Valley and its snow-capped peaks.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2vjgFcdYupDhzJm2ai3IAebyuZrGDcwBEQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwabohZJxnqRaw4fhWtDi55OGu7JqxC45aag&s", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Eagle Nest", city: "Hunza", category: "Adventure", rating: 4.9, price: 200, badge: "High Point", description: "The highest viewpoint in Hunza, famous for majestic golden hour vistas of Rakaposhi and Diran peaks.", image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80", bestTime: "Sunset", duration: "1-2 hours", isHiddenGem: true },
  { name: "Karimabad Bazaar", city: "Hunza", category: "Shopping", rating: 4.6, price: 0, badge: "Local", description: "A vibrant local market rich with handicrafts, precious gems, and dry fruits unique to Hunza.", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", bestTime: "Afternoon", duration: "1-2 hours" },
  { name: "Passu Cones", city: "Hunza", category: "Adventure", rating: 5.0, price: 0, badge: "Peaks", description: "Dramatic, jagged rock spires standing majestically along the Karakoram Highway near Passu village.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5C2IAudll1Umy02F7aso4tURGIJvXNgfMvw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5C2IAudll1Umy02F7aso4tURGIJvXNgfMvw&s", bestTime: "Morning", duration: "1-2 hours", isHiddenGem: true },
  { name: "Hunza Valley", city: "Hunza", category: "Nature", rating: 4.9, price: 0, badge: "Scenic", description: "A breathtakingly beautiful valley surrounded by towering peaks, apricot orchards, and ancient villages with a rich cultural heritage.", image: "https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/643599b38d0197001d05f18f.jpg", detailImage: "https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/643599b38d0197001d05f18f.jpg", bestTime: "Spring", duration: "Full day" },
  { name: "Altit Fort", city: "Hunza", category: "Historic", rating: 4.7, price: 400, badge: "Ancient", description: "One of the oldest forts in Gilgit-Baltistan, over 900 years old, offering spectacular views of Hunza Valley from its perch above the river.", image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/44/a1/60/altit-fort.jpg?w=1200&h=1200&s=1", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6_69RiANQ4xfL7xpD1Q4uNhZL5-rOfLCH9A&s", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Hussaini Suspension Bridge", city: "Hunza", category: "Adventure", rating: 4.8, price: 0, badge: "Thrilling", description: "One of the world's most dangerous bridges, a rickety wooden suspension bridge over the Hunza River with breathtaking scenery.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdzl7TwAb_-ZKs_buoggoATQYXbCgecA-9zQ&s", detailImage: "https://upload.wikimedia.org/wikipedia/commons/6/6d/The_bridge_of_Shepherds_-_Hussaini_Suspension_Bridge.jpg", bestTime: "Morning", duration: "1-2 hours", isHiddenGem: true },
  { name: "Naltar Valley", city: "Gilgit", category: "Nature", rating: 4.8, price: 0, badge: "Colors", description: "A hidden alpine valley famous for its tri-colored lakes, pine forests, and the Naltar Ski Resort — one of Pakistan's best winter destinations.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCgbZyYjeIK30e6dWUJBjInipEuoizUumjeQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmCX7ehZJ3XwkZ1Nt_HWXtvGOdRR2KeiBXuQ&s", bestTime: "Summer", duration: "Full day", isHiddenGem: true },
  { name: "Khunjerab Pass", city: "Hunza", category: "Adventure", rating: 4.9, price: 0, badge: "Border", description: "The world's highest paved international border crossing at 4,693m, connecting Pakistan and China on the ancient Silk Road.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL0OTf5emF4W9xchE39ZU8tRbjXuDDqxmUdg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL0OTf5emF4W9xchE39ZU8tRbjXuDDqxmUdg&s", bestTime: "Summer", duration: "Full day" },

  // ── SWAT ──
  { name: "Malam Jabba", city: "Swat", category: "Adventure", rating: 4.8, price: 1000, badge: "Ski", description: "A premier hill station and ski resort ideal for winter sports and mountain views.", image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80", bestTime: "Winter", duration: "Full day" },
  { name: "Mingora Bazaar", city: "Swat", category: "Shopping", rating: 4.2, price: 0, badge: "Market", description: "The main commercial hub of the valley, offering clothes, spices, and local crafts.", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", bestTime: "Morning", duration: "1-2 hours" },
  { name: "Swat River", city: "Swat", category: "Nature", rating: 4.7, price: 0, badge: "Scenic", description: "A fast-flowing, crystal-clear river coursing through the picturesque green valley.", image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&q=80", bestTime: "Morning", duration: "1-2 hours", isHiddenGem: true },
  { name: "Butkara Stupa", city: "Swat", category: "Historic", rating: 4.4, price: 200, badge: "Ruins", description: "Ancient Buddhist archaeological ruins unearthing Swat's profound and diverse history.", image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80", detailImage: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80", bestTime: "Morning", duration: "1-2 hours", isHiddenGem: true },
  { name: "Swat Valley", city: "Swat", category: "Nature", rating: 4.8, price: 0, badge: "Scenic", description: "The 'Switzerland of Pakistan', a lush green valley with snow-capped mountains, rivers, and beautiful meadows attracting tourists year-round.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7sMkjLQDqjJKy0lXDHCEGJBIVmlezpd-G0g&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7sMkjLQDqjJKy0lXDHCEGJBIVmlezpd-G0g&s", bestTime: "Summer", duration: "Full day" },
  { name: "Mahodand Lake", city: "Kalam", category: "Nature", rating: 4.9, price: 0, badge: "Alpine", description: "A pristine high-altitude lake in Kalam Valley, surrounded by snow-capped peaks and dense pine forests, accessible by jeep track.", image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/6a/b0/60/mahodand-lake-swat-kalam.jpg?w=800&h=400&s=1", detailImage: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/6a/b0/60/mahodand-lake-swat-kalam.jpg?w=800&h=400&s=1", bestTime: "Summer", duration: "Full day", isHiddenGem: true },
  { name: "Kalam Valley", city: "Swat", category: "Nature", rating: 4.8, price: 0, badge: "Lush", description: "A stunning upper valley of Swat featuring dense forests, glacial streams, and high-altitude meadows at 6,500 feet above sea level.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrDYkB6KnOeRPGvY-vLxdBI4F2dFS7v7V-bw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb1aO8O_39nXTjWXDL3DZaHa07X21F8ssVwA&s", bestTime: "Summer", duration: "Full day" },

  // ── GILGIT-BALTISTAN ──
  { name: "K2 Base Camp", city: "Skardu", category: "Adventure", rating: 5.0, price: 5000, badge: "Epic", description: "The base camp of the world's second-highest and most dangerous mountain at 8,611m. A legendary trekking destination through the Karakoram.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPLSkTjg6qRsqDncERd8F4WCCEsC-oWQG29A&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPLSkTjg6qRsqDncERd8F4WCCEsC-oWQG29A&s", bestTime: "Summer", duration: "Multi-day trek" },
  { name: "Concordia", city: "Skardu", category: "Adventure", rating: 5.0, price: 5000, badge: "K2 Trek", description: "The confluence point of the Baltoro Glacier, offering jaw-dropping views of four 8,000m peaks including K2, Broad Peak, and the Gasherbrums.", image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/3b/ee/38/view-from-concordia-motel.jpg?w=1000&h=1000&s=1", detailImage: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/3b/ee/38/view-from-concordia-motel.jpg?w=1000&h=1000&s=1", bestTime: "Summer", duration: "Multi-day trek", isHiddenGem: true },
  { name: "Nanga Parbat Base Camp", city: "Gilgit", category: "Adventure", rating: 4.9, price: 3000, badge: "9th Peak", description: "Base camp of Nanga Parbat, the world's ninth-highest mountain at 8,126m, known as the 'Killer Mountain'. Accessible via Fairy Meadows.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFYWA0otGfruBoY2UxYL74iKZsdLDdRNIa_g&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFYWA0otGfruBoY2UxYL74iKZsdLDdRNIa_g&s", bestTime: "Summer", duration: "Multi-day trek" },
  { name: "Fairy Meadows", city: "Gilgit", category: "Nature", rating: 5.0, price: 1000, badge: "Magical", description: "A stunning flat meadow at 3,300m with an unobstructed view of Nanga Parbat. Accessible by jeep and a steep hike, it's one of Pakistan's most scenic spots.", image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/d0/91/51/mesmerizing-view-of-fairy.jpg?w=800&h=-1&s=1", detailImage: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/d0/91/51/mesmerizing-view-of-fairy.jpg?w=800&h=-1&s=1", bestTime: "Summer", duration: "Full day" },
  { name: "Karakoram Highway", city: "Gilgit", category: "Adventure", rating: 4.9, price: 0, badge: "Silk Road", description: "The 'Eighth Wonder of the World', this remarkable highway connects Pakistan to China through the Karakoram mountain range at breathtaking altitudes.", image: "https://cdn.lambus.com/inspirations/67c58cc2a8d32a67c412845e/cover_photo/8a84b2d8-b57b-4309-6ddd-6a0345125a5a.jpeg?width=1800", detailImage: "https://cdn.lambus.com/inspirations/67c58cc2a8d32a67c412845e/cover_photo/8a84b2d8-b57b-4309-6ddd-6a0345125a5a.jpeg?width=1800", bestTime: "Summer", duration: "Multi-day drive" },
  { name: "Shigar Fort", city: "Skardu", category: "Historic", rating: 4.7, price: 500, badge: "Heritage", description: "A 400-year-old royal palace of the Amacha dynasty in Shigar Valley, now a luxury heritage hotel, set against dramatic desert-like landscapes.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRolB8wvrWQWuIScUDbtbCjX1HiBRzbsJVZEg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRolB8wvrWQWuIScUDbtbCjX1HiBRzbsJVZEg&s", bestTime: "Summer", duration: "2-3 hours" },
  { name: "Hushe Valley", city: "Skardu", category: "Adventure", rating: 4.8, price: 0, badge: "Trekkers", description: "A remote and spectacular valley in the Karakoram, serving as the gateway to Masherbrum and other lesser-trekked peaks.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsz9lvq2dQVJx92fw7ic67vc2zsy02BRipUw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGOZ1cdYD9S5a4-jMFGceUQXw5rzN0sx0-oQ&s", bestTime: "Summer", duration: "Multi-day trek", isHiddenGem: true },
  { name: "Skardu Valley", city: "Skardu", category: "Nature", rating: 4.9, price: 0, badge: "Gateway", description: "The main hub of Gilgit-Baltistan, a vast valley surrounded by soaring peaks, cold deserts, and the mighty Indus River flowing through its heart.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIW77apADFEhy3fP27NievUqB7ycvn_zfJRA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqCZUN3QfCpHP1TGrV2SBRUE_IlqZhZWcFSA&s", bestTime: "Summer", duration: "Full day" },
  { name: "Deosai National Park", city: "Skardu", category: "Nature", rating: 4.9, price: 500, badge: "Plateau", description: "The world's second-highest plateau at 4,114m above sea level, a vast alpine wilderness and home to the Himalayan brown bear and rare wildflowers.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOXa880po1MfDrxTdu4lBK9rGfHHEwrkByIw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOXa880po1MfDrxTdu4lBK9rGfHHEwrkByIw&s", bestTime: "Summer", duration: "Full day" },
  { name: "Deosai Sheosar Lake", city: "Skardu", category: "Nature", rating: 4.9, price: 500, badge: "High Altitude", description: "A stunningly pristine high-altitude lake sitting at 4,142m within Deosai National Park, known for its deep blue waters and surrounding wildflower meadows.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtBHURwoG75qgF_d_hHsxmTqWPeVuNYPJ8ng&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtBHURwoG75qgF_d_hHsxmTqWPeVuNYPJ8ng&s", bestTime: "Summer", duration: "Full day", isHiddenGem: true },
  { name: "Katpana Cold Desert", city: "Skardu", category: "Nature", rating: 4.7, price: 0, badge: "Unique", description: "The world's highest cold desert near Skardu, with vast sand dunes surrounded by snow-capped mountains — a surreal landscape unlike anywhere else.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw1O6Qo0YrSEALq86ud-SDtUjEDKwSHT2iCQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Rv5YZ6P4oYJFiqLQN6aAlhnHDHJ3LI7lQA&s", bestTime: "Summer", duration: "2-3 hours", isHiddenGem: true },
  { name: "Shangrila Resort", city: "Skardu", category: "Nature", rating: 4.8, price: 2000, badge: "Paradise", description: "Known as 'Heaven on Earth', Shangrila Resort sits beside the serene Upper Kachura Lake, offering breathtaking mountain views and unique airplane-shaped restaurant.", image: "https://ik.imgkit.net/3vlqs5axxjf/external/http://images.ntmllc.com/v4/hotel/M57/M57472/M57472_EXT_Z47046.JPG?tr=w-1200%2Cfo-auto", detailImage: "https://shangrilaresorts.com.pk/storage/2020/11/PHOTO-2020-08-29-14-56-32-1024x768.jpg", bestTime: "Summer", duration: "Full day" },
  { name: "Phander Valley", city: "Gilgit", category: "Nature", rating: 4.8, price: 0, badge: "Hidden", description: "An enchanting, less-visited valley with emerald green lakes, lush meadows, and mirror-like reflections of the surrounding peaks.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpj3DqXbn5t8hnaVCZxBPpX0WxnitnYiCBsw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM8dmFRSvetmO3fFJjN7MO73IlxgaRNNpEUw&s", bestTime: "Summer", duration: "Full day", isHiddenGem: true },

  // ── KP / NORTHERN AREAS ──
  { name: "Chitral Valley", city: "Chitral", category: "Nature", rating: 4.7, price: 0, badge: "Remote", description: "A magnificent valley bordering Afghanistan, home to the unique Kalash people and diverse landscapes ranging from snow peaks to subtropical forests.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0NnNJHeXRbS1ulHn70t371sNuC7o8smG2aA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKjioTDgGHLgDLcHpF6ZO0fAGtaNE7yFcAkw&s", bestTime: "Summer", duration: "Full day" },
  { name: "Kalash Valley", city: "Chitral", category: "Culture", rating: 4.8, price: 200, badge: "Unique", description: "Home to the ancient Kalash people, with their distinct polytheistic religion, colorful festivals, and vibrant traditional attire unlike any other in Pakistan.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnHB0eXF74YtZ-nmHY0HOy4loH-ITky_QHdg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnHB0eXF74YtZ-nmHY0HOy4loH-ITky_QHdg&s", bestTime: "Spring", duration: "Full day", isHiddenGem: true },
  { name: "Shandur Pass", city: "Chitral", category: "Adventure", rating: 4.8, price: 0, badge: "Polo Festival", description: "The world's highest polo ground at 3,700m, hosting the famous annual Shandur Polo Festival, connecting Chitral and Gilgit in spectacular mountain scenery.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI3SdjAjjMRI63gNYkzg2o3uirPiLMH0KN4Q&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI3SdjAjjMRI63gNYkzg2o3uirPiLMH0KN4Q&s", bestTime: "Summer", duration: "Full day", isHiddenGem: true },
  { name: "Babusar Pass", city: "Kaghan", category: "Adventure", rating: 4.8, price: 0, badge: "High Pass", description: "A stunning mountain pass at 4,173m connecting Kaghan Valley to Gilgit-Baltistan, offering panoramic views of the Karakoram and Himalayan ranges.", image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/81/61/3e/babusar-pass.jpg?w=900&h=-1&s=1", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMvw6zi7c6MgbmPKNbRkjbLFkNHHGDl1-Opg&s", bestTime: "Summer", duration: "Full day" },
  { name: "Saiful Malook Lake", city: "Kaghan", category: "Nature", rating: 5.0, price: 500, badge: "Legendary", description: "Pakistan's most famous mountain lake at 3,224m, surrounded by snow-capped peaks. Site of the famous Punjabi love legend of Saif ul Malook and Badr ul Jammal.", image: "https://visitsilkroad.org/wp-content/uploads/2021/04/Saif-Ul-Malook-Lake-featured_image2.jpg", detailImage: "https://visitsilkroad.org/wp-content/uploads/2021/04/Saif-Ul-Malook-Lake-featured_image2.jpg", bestTime: "Summer", duration: "Full day" },
  { name: "Shogran", city: "Kaghan", category: "Nature", rating: 4.7, price: 0, badge: "Hill Station", description: "A charming hill station in Kaghan Valley at 7,749 feet, offering stunning views of Musa Ka Musalla peak and the surrounding forests.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlyjD7yTZ-cPOpX8jv3AmHxeIPA5kBSjqQ3A&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5IPxhdHNrQ_va4uVlr0jjKuk49XBXdtev-Q&s", bestTime: "Summer", duration: "Full day" },
  { name: "Kumrat Valley", city: "Dir", category: "Nature", rating: 4.8, price: 0, badge: "Untouched", description: "A breathtakingly pristine valley in Upper Dir, with dense pine forests, clear streams, and alpine meadows that remain largely off the beaten tourist path.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZY2_gbAatrQ46aCcwx83g9lW6U_C0QJLuWA&s", detailImage: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/d9/3d/64/kumrat-urdu-is-a-valley.jpg?w=900&h=500&s=1", bestTime: "Summer", duration: "Full day", isHiddenGem: true },
  { name: "Takht-e-Bahi", city: "Mardan", category: "Historic", rating: 4.6, price: 200, badge: "Buddhist", description: "A UNESCO World Heritage Buddhist monastic complex dating to the 1st century AD, one of the best-preserved Gandhara ruins in Pakistan.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHu3_vCt0SZEJUBr5--BWRJDclEoMliFwhWA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjY9xBtO9ILNaJRdguZj3gxVWXOAJTaiBJLg&s", bestTime: "Morning", duration: "2-3 hours" },
  { name: "Peshawar Museum", city: "Peshawar", category: "Culture", rating: 4.6, price: 100, badge: "Gandhara", description: "Pakistan's premier museum for Gandhara art and Buddhist sculpture, housing an extraordinary collection of artifacts from the ancient Gandhara civilization.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Peshawar_Museum_Hall.jpg/330px-Peshawar_Museum_Hall.jpg", detailImage: "https://i.dawn.com/primary/2014/08/5402430b92598.jpg", bestTime: "Morning", duration: "2-3 hours" },

  // ── AJK / KASHMIR ──
  { name: "Neelum Valley", city: "Neelum Valley", category: "Nature", rating: 4.9, price: 0, badge: "Kashmir", description: "A pristine crescent-shaped valley in AJK running parallel to the Line of Control, famous for its emerald forests, turquoise rivers, and charming villages.", image: "https://res.cloudinary.com/dyiffrkzh/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_center,h_400,q_auto,w_700/v1718952554/banbanjara/j4gff29jmaljv4bntd3z.jpg", detailImage: "https://res.cloudinary.com/dyiffrkzh/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_center,h_400,q_auto,w_700/v1718952554/banbanjara/j4gff29jmaljv4bntd3z.jpg", bestTime: "Summer", duration: "Multi-day" },
  { name: "Aran Kel", city: "Neelum Valley", category: "Nature", rating: 4.8, price: 0, badge: "Remote", description: "An isolated and strikingly beautiful village in Neelum Valley accessible only by a footbridge over the Neelum River, offering an unspoiled view of Kashmir.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5i-6yvvN5bO4T9fR9HSQy2Pf1byVR8EIGpQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5i-6yvvN5bO4T9fR9HSQy2Pf1byVR8EIGpQ&s", bestTime: "Summer", duration: "Full day", isHiddenGem: true },
  { name: "Rati Gali Lake", city: "Neelum Valley", category: "Nature", rating: 4.9, price: 0, badge: "Alpine", description: "A spectacular high-altitude glacial lake in Neelum Valley at 3,623m, surrounded by snow fields and rocky terrain accessible through a scenic trek.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3uFknnsyGKfe-fpg8cCA26zymXpyae_zvYg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3uFknnsyGKfe-fpg8cCA26zymXpyae_zvYg&s", bestTime: "Summer", duration: "Full day trek", isHiddenGem: true },
  { name: "Leepa Valley", city: "AJK", category: "Nature", rating: 4.7, price: 0, badge: "Scenic", description: "A stunningly beautiful valley in AJK known for its cherry and apple orchards, terraced fields, and unmatched views of snow-capped Himalayan peaks.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7qp42ZEJ8FMnpDk7M4m9ULKuN--dDUAi4tA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn4IPG2aXIcpCNOetP5sKf4VXzlcgudnLTJA&s", bestTime: "Spring", duration: "Full day", isHiddenGem: true },

  // ── SINDH ──
  { name: "Sehwan Sharif", city: "Sindh", category: "Religious", rating: 4.7, price: 0, badge: "Shrine", description: "Home to the revered shrine of Lal Shahbaz Qalandar, a Sufi saint. The ecstatic dhamaal drum ceremony held every Thursday draws thousands of devotees.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMkEYQNqcG26d-wpI1TJlFWh1CGumXPXfMgQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMkEYQNqcG26d-wpI1TJlFWh1CGumXPXfMgQ&s", bestTime: "Evening", duration: "2-3 hours" },
  { name: "Mohenjo Daro", city: "Sindh", category: "Historic", rating: 4.8, price: 300, badge: "Ancient", description: "One of the world's earliest major urban settlements, Mohenjo Daro dates to around 2500 BCE and is a UNESCO World Heritage Site of the Indus Valley Civilization.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4sWmVzwKol_BSx91wdH7p5wQVVi2STVoITA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4ioNZrqVV6BNN1ou8heKeZeHpM52z_PkpfQ&s", bestTime: "Morning", duration: "3-4 hours" },
  { name: "Ranikot Fort", city: "Sindh", category: "Historic", rating: 4.6, price: 100, badge: "Great Wall", description: "Known as the 'Great Wall of Sindh', Ranikot is the world's largest fort with a 32km perimeter wall, dating back to the 19th century in the Kirthar Range.", image: "https://taxilamuseum.com/wp-content/uploads/2023/08/Rohtas-Fort.jpg", detailImage: "https://www.aljazeera.com/wp-content/uploads/2019/06/665003303001_6044014223001_6044018988001-th.jpeg?resize=1200%2C675", bestTime: "Morning", duration: "Half day", isHiddenGem: true },
  { name: "Shah Jahan Mosque", city: "Thatta", category: "Religious", rating: 4.7, price: 100, badge: "Mughal", description: "A magnificent 17th-century Mughal mosque in Thatta famous for its extraordinary acoustics — a whisper near the dome can be heard clearly at the other end.", image: "https://cdn-blog.zameen.com/blog/wp-content/uploads/2019/08/cover-image-28.jpg", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7oJBkdpHYOklr1sXjHTPIhnxkSg2DwquJWA&s", bestTime: "Morning", duration: "1-2 hours", isHiddenGem: true },

  // ── BALOCHISTAN ──
  { name: "Kund Malir Beach", city: "Gwadar", category: "Beach", rating: 4.8, price: 0, badge: "Pristine", description: "One of Pakistan's most beautiful and untouched beaches along the Makran Coast, with golden sands, turquoise waters, and dramatic rocky cliffs.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAjDqVTTnfbx8sfAlaRY25jLauVeMPOmaLHg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAjDqVTTnfbx8sfAlaRY25jLauVeMPOmaLHg&s", bestTime: "Winter", duration: "Full day" },
  { name: "Makran Coastal Highway", city: "Gwadar", category: "Adventure", rating: 4.7, price: 0, badge: "Coastal", description: "A scenic coastal highway stretching 653km along the Arabian Sea, passing through rugged terrain, pristine beaches, and fishing villages in Balochistan.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf17vwWl2S1laOg72Ho_a-RwoPj6wWOwOOeg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf17vwWl2S1laOg72Ho_a-RwoPj6wWOwOOeg&s", bestTime: "Winter", duration: "Multi-day drive" },
  { name: "Astola Island", city: "Gwadar", category: "Beach", rating: 4.7, price: 2000, badge: "Island", description: "Pakistan's largest offshore island in the Arabian Sea, known for its pristine beaches, sea turtle nesting sites, and excellent diving and snorkelling spots.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwuo4krZdp1mTTzyk5v2j7ZxCyjtCPT8AJWQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzbYde5TcKp2mn7KGuArVBwjaTUO-CHJ6P3w&s", bestTime: "Winter", duration: "Full day", isHiddenGem: true },
  { name: "Hingol National Park", city: "Balochistan", category: "Nature", rating: 4.7, price: 200, badge: "Largest Park", description: "Pakistan's largest national park spanning 6,100 km², featuring the Hindu Hinglaj shrine, Princess of Hope rock formation, and diverse desert wildlife.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7tEGS_0NCREH49wmYhSjYj8bcQTjGIJsA9Q&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv6mnDwSqhkhUjsBHSbwuxGx71OccBfS3Z3g&s", bestTime: "Winter", duration: "Full day" },

  // ── PUNJAB (OTHER) ──
  { name: "Derawar Fort", city: "Bahawalpur", category: "Historic", rating: 4.7, price: 200, badge: "Desert Fort", description: "A massive 9th-century square fort rising from the Cholistan Desert, with 40 bastions each 30m in height, one of the most spectacular fortresses in Pakistan.", image: "https://www.pakistanhc.lk/wp-content/uploads/2018/10/Derawar-Fort-Bahawalpur-960x640.jpg", detailImage: "https://www.pakistanhc.lk/wp-content/uploads/2018/10/Derawar-Fort-Bahawalpur-960x640.jpg", bestTime: "Morning", duration: "2-3 hours", isHiddenGem: true },

  // ── MULTAN ──
  { name: "Shah Rukn-e-Alam", city: "Multan", category: "Religious", rating: 4.8, price: 0, badge: "Sufi Shrine", description: "A majestic 14th-century Sufi shrine and one of the finest examples of Tughlaq-period architecture in the subcontinent, dedicated to the saint Shah Rukn-e-Alam.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcjfRj7-B78PIfxIVWkVoem0qL0zxONpFlsQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcjfRj7-B78PIfxIVWkVoem0qL0zxONpFlsQ&s", bestTime: "Morning", duration: "1-2 hours" },

  // ── HIDDEN GEMS ──────────────────────────────────────────────────────────
  { name: "Deosai Brown Bear Tracking", city: "Skardu", category: "Adventure", rating: 5.0, price: 1000, badge: "LEGENDARY", rarity: "LEGENDARY", description: "Rare dawn tracking experience in the world's second-highest plateau — Deosai is one of the last wild habitats of the Himalayan Brown Bear.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlKBwY7tMiUV88-m5avSWCofS61BxlCe27Gw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlKBwY7tMiUV88-m5avSWCofS61BxlCe27Gw&s", bestTime: "Morning", duration: "Full day", isHiddenGem: true, tags: ["Wildlife", "Adventure", "Nature"] },

  { name: "Fairy Meadows Stargazing", city: "Gilgit", category: "Nature", rating: 5.0, price: 500, badge: "LEGENDARY", rarity: "LEGENDARY", description: "Spend the night at 3,300m under a sky so clear the Milky Way is visible to the naked eye, with Nanga Parbat silhouetted against the stars.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcInaX7O8u16cnT92WsnPqau0XQacQAUj8Lw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcInaX7O8u16cnT92WsnPqau0XQacQAUj8Lw&s", bestTime: "Night", duration: "Overnight", isHiddenGem: true, tags: ["Stargazing", "Night Sky", "Camping"] },

  { name: "Ratti Gali at First Snowfall", city: "Neelum Valley", category: "Nature", rating: 4.9, price: 0, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Trek to the glacial Ratti Gali Lake right after the first autumn snowfall — a short window when the landscape is transformed into a silent white world.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoJb1e9b0xuODswDC2S14KyC441ECO2tqtQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoJb1e9b0xuODswDC2S14KyC441ECO2tqtQ&s", bestTime: "Autumn", duration: "Full day trek", isHiddenGem: true, tags: ["Snow", "Trek", "Kashmir"] },

  { name: "Leepa Valley Apple Harvest", city: "AJK", category: "Nature", rating: 4.8, price: 0, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Visit Leepa Valley during the September apple harvest — locals invite you to pick fruit straight from the trees in terraced orchards overlooking the peaks.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd1Bro2CeO-vC_ExNiSF-AiU3gOcsrpR7mUQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd1Bro2CeO-vC_ExNiSF-AiU3gOcsrpR7mUQ&s", bestTime: "Autumn", duration: "Full day", isHiddenGem: true, tags: ["Harvest", "Culture", "Kashmir"] },

  { name: "Derawar Fort Sunrise", city: "Bahawalpur", category: "Historic", rating: 4.9, price: 200, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Watch the desert sun rise over the 30m-high black bastions of Derawar Fort — an experience that requires camping overnight in the Cholistan Desert.", image: "https://www.shutterstock.com/image-photo/derawar-fort-large-square-fortress-260nw-1101137141.jpg", detailImage: "https://www.shutterstock.com/image-photo/derawar-fort-large-square-fortress-260nw-1101137141.jpg", bestTime: "Dawn", duration: "Overnight", isHiddenGem: true, tags: ["Desert", "Sunrise", "History"] },

  { name: "Makli Necropolis at Dusk", city: "Thatta", category: "Historic", rating: 4.8, price: 100, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "One of the world's largest necropolises with 125,000 tombs — visited at dusk when the golden light turns the sandstone monuments into glowing silhouettes.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEAfTCN1XS8vDvNg1nSuRAjahM0qKuSi_IQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEAfTCN1XS8vDvNg1nSuRAjahM0qKuSi_IQ&s", bestTime: "Sunset", duration: "2-3 hours", isHiddenGem: true, tags: ["UNESCO", "History", "Photography"] },

  { name: "Gorakh Hill Stargazing", city: "Balochistan", category: "Nature", rating: 4.9, price: 300, badge: "LEGENDARY", rarity: "LEGENDARY", description: "At 1,734m in the heart of Sindh's Kirthar Range, Gorakh Hill gets so cold clouds form below you — the highest dark-sky site in Sindh for astrophotography.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR38PGW0okfbHXqvaTiQYT-XR8Pl8RvAfcA3Q&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR38PGW0okfbHXqvaTiQYT-XR8Pl8RvAfcA3Q&s", bestTime: "Night", duration: "Overnight", isHiddenGem: true, tags: ["Stargazing", "Night Sky", "Remote"] },

  { name: "Kund Malir Beach Overnight Camping", city: "Gwadar", category: "Beach", rating: 4.9, price: 0, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Camp overnight on Kund Malir's pristine golden sands with the Makran cliffs as your backdrop and a sky full of stars above the Arabian Sea.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaeSGucVk_rSn-3U-iF451yUloYXDVztDtOQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaeSGucVk_rSn-3U-iF451yUloYXDVztDtOQ&s", bestTime: "Night", duration: "Overnight", isHiddenGem: true, tags: ["Beach", "Camping", "Stars"] },

  { name: "Astola Island Camping", city: "Gwadar", category: "Beach", rating: 4.9, price: 2000, badge: "LEGENDARY", rarity: "LEGENDARY", description: "Spend the night on Pakistan's only offshore island — a 6.7 km² pristine island with sea turtles, deserted beaches, and zero light pollution.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMpWpn33fFDo21F8BO556hCNSLg1e9A54cXA&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMpWpn33fFDo21F8BO556hCNSLg1e9A54cXA&s", bestTime: "Night", duration: "Overnight", isHiddenGem: true, tags: ["Island", "Camping", "Sea Turtles"] },

  { name: "Hinglaj Mata Pilgrimage", city: "Balochistan", category: "Religious", rating: 4.8, price: 0, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Pakistan's largest Hindu pilgrimage — over 100,000 devotees trek through the Makran desert to the ancient cave shrine of Hinglaj Mata every April.", image: "https://static.toiimg.com/thumb/msid-109525095,imgsize-210290,width-400,resizemode-4/109525095.jpg", detailImage: "https://static.toiimg.com/thumb/msid-109525095,imgsize-210290,width-400,resizemode-4/109525095.jpg", bestTime: "Spring", duration: "Full day", isHiddenGem: true, tags: ["Pilgrimage", "Culture", "Hindu Festival"] },

  { name: "Multan Ramadan Rooftop Iftar", city: "Multan", category: "Food", rating: 4.9, price: 500, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Join a local family on their rooftop in the City of Saints for Iftar — traditional Multani dishes shared under the stars during Ramadan as the call to prayer echoes.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX7IZcS9HdZ352Mk2cevcmvWa2qqeVzGVCYQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX7IZcS9HdZ352Mk2cevcmvWa2qqeVzGVCYQ&s", bestTime: "Evening", duration: "2-3 hours", isHiddenGem: true, tags: ["Ramadan", "Food", "Culture"] },

  { name: "Naran Trout Fishing at Dawn", city: "Kaghan", category: "Adventure", rating: 4.8, price: 300, badge: "RARE", rarity: "RARE", description: "Cast a line in the icy Kunhar River at first light — local guides know the spots where wild brown trout school in the crystal glacial waters of Kaghan.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSawwmsJ19YMS8z4hRKQQbn-qB5_9q0PzRzzg&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSawwmsJ19YMS8z4hRKQQbn-qB5_9q0PzRzzg&s", bestTime: "Dawn", duration: "3-4 hours", isHiddenGem: true, tags: ["Fishing", "Nature", "Dawn"] },

  { name: "Thar Desert Overnight Camel Safari", city: "Sindh", category: "Adventure", rating: 4.9, price: 2000, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Ride into the Thar Desert at dusk on camelback, sleep under a canopy of stars, and wake to the sound of morning prayers drifting from distant villages.", image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/11/d7/cf/f4.jpg", detailImage: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/11/d7/cf/f4.jpg", bestTime: "Night", duration: "Overnight", isHiddenGem: true, tags: ["Desert", "Camel", "Safari"] },

  { name: "Ziarat Ancient Juniper Trees", city: "Balochistan", category: "Nature", rating: 4.8, price: 0, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Walk among juniper trees that are 5,000 years old — the second-largest juniper forest in the world, set in the cool heights of Ziarat district.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6fXzntAHBKoWuaAozWp21NfwCG6d5FCIKVw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6fXzntAHBKoWuaAozWp21NfwCG6d5FCIKVw&s", bestTime: "Morning", duration: "Half day", isHiddenGem: true, tags: ["Ancient Trees", "Nature", "Rare"] },

  { name: "Gilgit Apricot Blossom Villages", city: "Gilgit", category: "Nature", rating: 4.9, price: 0, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Every April, the villages of Gilgit-Baltistan explode in pink and white apricot blossoms — a 10-day window locals call the most beautiful weeks of the year.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsyruoIYbKfAqu-hx8EtEssC6s7hKBmnQhxQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsyruoIYbKfAqu-hx8EtEssC6s7hKBmnQhxQ&s", bestTime: "Spring", duration: "Full day", isHiddenGem: true, tags: ["Blossom", "Spring", "Photography"] },

  { name: "Takht-i-Bahi Night Watchman Tour", city: "Mardan", category: "Historic", rating: 4.7, price: 200, badge: "RARE", rarity: "RARE", description: "Join the site's night watchman after closing for a private candlelit walk through the 2,000-year-old Buddhist ruins — an eerie, unforgettable experience.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRumiCRGzggu0n-5HnfkhwZWfceQUH0YvJ6Sw&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRumiCRGzggu0n-5HnfkhwZWfceQUH0YvJ6Sw&s", bestTime: "Night", duration: "2-3 hours", isHiddenGem: true, tags: ["Night Tour", "History", "Gandhara"] },

  { name: "Katas Raj Hindu Festival Night", city: "Rawalpindi", category: "Religious", rating: 4.8, price: 0, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Witness the ancient Katas Raj Shiv temple come alive during Hindu festival nights — the sacred lake glows with oil lamps reflected in waters Hindus believe were formed from the tears of Lord Shiva.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcNOiRJlktQ576Hxk6CwbL9UYlRrQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcNOiRJlktQ576Hxk6CwbL9UYlRrQ&s", bestTime: "Night", duration: "3-4 hours", isHiddenGem: true, tags: ["Hindu Festival", "Temple", "Night"] },

  { name: "Hoper Glacier Walk", city: "Gilgit", category: "Adventure", rating: 4.9, price: 500, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Walk on the surface of Hoper Glacier in Nagar Valley — a dramatic river of ancient blue ice descending from the Karakoram peaks above.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", bestTime: "Morning", duration: "Full day", isHiddenGem: true, tags: ["Glacier", "Trekking", "Adventure"] },

  { name: "Sehwan Thursday Night Dhamaal", city: "Sindh", category: "Religious", rating: 4.9, price: 0, badge: "LEGENDARY", rarity: "LEGENDARY", description: "Every Thursday night at Lal Shahbaz Qalandar's shrine, thousands of devotees fall into trance-like dhamaal dancing to the beating of dhol drums — one of the most transcendent experiences in Pakistan.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", bestTime: "Night", duration: "3-4 hours", isHiddenGem: true, tags: ["Sufi", "Dhamaal", "Festival"] },

  { name: "Margalla Sunset Trail", city: "Islamabad", category: "Nature", rating: 4.7, price: 0, badge: "RARE", rarity: "RARE", description: "Hike Trail 3 of the Margalla Hills in the final hour of daylight when the forest glows amber and the entire capital spreads below you in the fading light.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", bestTime: "Sunset", duration: "2-3 hours", isHiddenGem: true, tags: ["Hiking", "Sunset", "Nature"] },

  { name: "Khanpur Cliff Jumping Session", city: "Haripur", category: "Adventure", rating: 4.8, price: 300, badge: "RARE", rarity: "RARE", description: "Local youth have turned Khanpur Dam's limestone cliffs into an unofficial jumping spot — heights range from 5m to 20m into the emerald green reservoir.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", bestTime: "Afternoon", duration: "Half day", isHiddenGem: true, tags: ["Cliff Jumping", "Water Sports", "Thrill"] },

  { name: "Simli Dam Night Fishing", city: "Islamabad", category: "Adventure", rating: 4.6, price: 200, badge: "RARE", rarity: "RARE", description: "A hidden dam just 40km from Islamabad where locals fish through the night — bring a fire, a rod, and enjoy the silence broken only by crickets and water.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", bestTime: "Night", duration: "Overnight", isHiddenGem: true, tags: ["Fishing", "Night", "Hidden"] },

  { name: "Anarkali Rare Bookshop", city: "Lahore", category: "Culture", rating: 4.7, price: 0, badge: "RARE", rarity: "RARE", description: "Deep in Anarkali Bazaar, a century-old bookshop stocks out-of-print Urdu poetry, colonial-era maps of Punjab, and Partition-era first editions — treasures unknown to most tourists.", image: "https://i.dawn.com/primary/2021/10/617dbc242bcf5.jpg", detailImage: "https://i.dawn.com/primary/2021/10/617dbc242bcf5.jpg", bestTime: "Morning", duration: "1-2 hours", isHiddenGem: true, tags: ["Books", "History", "Hidden"] },

  { name: "Gawalmandi After Midnight Food", city: "Lahore", category: "Food", rating: 4.9, price: 800, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "After midnight, Gawalmandi transforms — the same stalls that close at 10pm reopen for a secret second service of siri paye, nihari, and chai for night workers, policemen, and the occasional foodie.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", bestTime: "Night", duration: "2-3 hours", isHiddenGem: true, tags: ["Street Food", "Late Night", "Lahori"] },

  { name: "Wazir Khan Mosque Before Dawn", city: "Lahore", category: "Religious", rating: 5.0, price: 0, badge: "LEGENDARY", rarity: "LEGENDARY", description: "Arrive at Wazir Khan Mosque 30 minutes before Fajr — the caretaker opens early for those who know to ask, and you'll experience the 17th-century faience tile work in complete silence, lit only by lanterns.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoJb1e9b0xuODswDC2S14KyC441ECO2tqtQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoJb1e9b0xuODswDC2S14KyC441ECO2tqtQ&s", bestTime: "Dawn", duration: "1-2 hours", isHiddenGem: true, tags: ["Mosque", "Dawn", "Hidden Access"] },

  { name: "Kemari Fisherman Docks at 3AM", city: "Karachi", category: "Culture", rating: 4.8, price: 0, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "At 3AM, the Kemari docks roar to life — hundreds of fishermen return with the night's catch, auctioning tonnes of fresh seafood in a chaotic, aromatic spectacle no guidebook mentions.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoJb1e9b0xuODswDC2S14KyC441ECO2tqtQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoJb1e9b0xuODswDC2S14KyC441ECO2tqtQ&s", bestTime: "Night", duration: "2-3 hours", isHiddenGem: true, tags: ["Fish Market", "Night", "Local Life"] },

  { name: "Burns Road Midnight Halwa Puri", city: "Karachi", category: "Food", rating: 4.9, price: 400, badge: "RARE", rarity: "RARE", description: "The original Burns Road halwa puri shops open at midnight and serve until dawn — fluffy puris, channay, and sooji halwa eaten at 2am is a Karachi rite of passage.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoJb1e9b0xuODswDC2S14KyC441ECO2tqtQ&s", detailImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoJb1e9b0xuODswDC2S14KyC441ECO2tqtQ&s", bestTime: "Night", duration: "1-2 hours", isHiddenGem: true, tags: ["Street Food", "Midnight", "Karachi Classic"] },

  { name: "Saddar Old Irani Cafe", city: "Karachi", category: "Culture", rating: 4.7, price: 200, badge: "RARE", rarity: "RARE", description: "A handful of Irani cafés in Saddar have operated since the 1940s — strong chai, bun maska, and conversations with regulars who remember pre-Partition Karachi.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", bestTime: "Morning", duration: "1-2 hours", isHiddenGem: true, tags: ["Heritage", "Cafe", "History"] },

  { name: "Hawks Bay Sea Turtle Night", city: "Karachi", category: "Nature", rating: 5.0, price: 0, badge: "LEGENDARY", rarity: "LEGENDARY", description: "Between July and December, green and olive ridley sea turtles crawl ashore at Hawks Bay to nest. WWF guides take small groups to witness this prehistoric spectacle in complete darkness.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", bestTime: "Night", duration: "3-4 hours", isHiddenGem: true, tags: ["Sea Turtles", "Conservation", "Night"] },

  { name: "Manora Island at Dawn", city: "Karachi", category: "Nature", rating: 4.7, price: 300, badge: "RARE", rarity: "RARE", description: "Take the first boat to Manora Island before 6am — the fishing village wakes quietly, the lighthouse glows, and you'll have the entire beach to yourself before day trippers arrive.", image: "https://i.dawn.com/primary/2021/10/617dbc242bcf5.jpg", detailImage: "https://i.dawn.com/primary/2021/10/617dbc242bcf5.jpg", bestTime: "Dawn", duration: "Half day", isHiddenGem: true, tags: ["Island", "Dawn", "Quiet"] },

  { name: "Peshawari Namkeen Chai at Night", city: "Peshawar", category: "Food", rating: 4.8, price: 100, badge: "RARE", rarity: "RARE", description: "In the old city's teahouses, pink Kashmiri chai mixed with cardamom and pistachios is served from giant samovars late into the night — a tradition unchanged for 200 years.", image: "https://i.dawn.com/primary/2021/10/617dbc242bcf5.jpg", detailImage: "https://i.dawn.com/primary/2021/10/617dbc242bcf5.jpg", bestTime: "Night", duration: "1-2 hours", isHiddenGem: true, tags: ["Chai", "Culture", "Old City"] },

  { name: "Kalash Chilam Joshi Festival Night", city: "Chitral", category: "Culture", rating: 5.0, price: 0, badge: "LEGENDARY", rarity: "LEGENDARY", description: "The ancient Kalash spring festival Chilam Joshi peaks at night — women in beaded headdresses dance around bonfires, singing songs in a language that predates Islam in these valleys.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", bestTime: "Night", duration: "Full night", isHiddenGem: true, tags: ["Kalash", "Festival", "Ancient Culture"] },

  { name: "Shandur Polo Festival Camping", city: "Chitral", category: "Adventure", rating: 4.9, price: 1000, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Camp at 3,700m during the world's highest polo festival — spend nights in tents surrounded by Chitral and Gilgit tribesmen, with bonfires and music echoing across the plateau.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", bestTime: "Summer", duration: "Overnight", isHiddenGem: true, tags: ["Polo", "Festival", "Camping"] },

  { name: "Nathiagali Cloud Forest Walk", city: "Kaghan", category: "Nature", rating: 4.7, price: 0, badge: "RARE", rarity: "RARE", description: "On misty mornings in Nathiagali, the pine forest disappears into low cloud — a short walk on the Miranjani Trail becomes a surreal walk through a green cloud world.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", bestTime: "Morning", duration: "2-3 hours", isHiddenGem: true, tags: ["Cloud Forest", "Mist", "Hiking"] },

  { name: "Attabad Underwater Village Tour", city: "Hunza", category: "Adventure", rating: 4.9, price: 800, badge: "ULTRA_RARE", rarity: "ULTRA_RARE", description: "Boat over the flooded remains of Gulmit village, submerged beneath Attabad Lake's turquoise waters in 2010 — on clear days you can see rooftops below the surface.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-2.jpg", bestTime: "Morning", duration: "2-3 hours", isHiddenGem: true, tags: ["Underwater", "Boat", "Unique"] },

  { name: "Baltit Fort Sunset on Roof", city: "Hunza", category: "Historic", rating: 5.0, price: 500, badge: "LEGENDARY", rarity: "LEGENDARY", description: "The Baltit Fort guide allows small groups to climb to the roof terrace at sunset — the 900-year-old fort glows amber while Rakaposhi, Ultar Sar, and Lady Finger peaks all turn gold simultaneously.", image: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", detailImage: "https://northbackend.northonwheels.com/storage/uploads/Hoper-Glacier-1.jpg", bestTime: "Sunset", duration: "1-2 hours", isHiddenGem: true, tags: ["Fort", "Sunset", "Hunza"] },
];

const hotels = [
  // ── ISLAMABAD ──
  { name: "Serena Hotel Islamabad", city: "Islamabad", area: "Diplomatic Enclave", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80", stars: 5, rating: 9.3, reviewCount: 2150, price: 35000, originalPrice: 40000, badge: "Top Luxury", badgeClass: "luxury", amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Gym"] },
  { name: "Marriott Islamabad", city: "Islamabad", area: "Aga Khan Road", image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80", stars: 5, rating: 8.9, reviewCount: 1800, price: 30000, originalPrice: 35000, badge: "Popular", badgeClass: "", amenities: ["WiFi", "Pool", "Restaurant", "Gym", "Parking"] },
  { name: "PC Hotel Islamabad", city: "Islamabad", area: "Blue Area", image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80", stars: 4, rating: 8.5, reviewCount: 1200, price: 18000, originalPrice: 22000, badge: "Business", badgeClass: "", amenities: ["WiFi", "Restaurant", "Gym", "Parking"] },
  { name: "Envoy Continental", city: "Islamabad", area: "Blue Area", image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", stars: 3, rating: 8.1, reviewCount: 850, price: 8000, originalPrice: 10000, badge: "Value", badgeClass: "", amenities: ["WiFi", "Restaurant", "Parking"] },
  { name: "Islamabad Backpackers Hostel", city: "Islamabad", area: "F-6", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80", stars: 1, rating: 7.9, reviewCount: 400, price: 2500, originalPrice: 0, badge: "Budget", badgeClass: "", amenities: ["WiFi", "Common Room", "Lockers"] },

  // ── LAHORE ──
  { name: "Pearl Continental Lahore", city: "Lahore", area: "Mall Road", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80", stars: 5, rating: 9.1, reviewCount: 2500, price: 32000, originalPrice: 38000, badge: "Top Luxury", badgeClass: "luxury", amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Gym"] },
  { name: "Avari Hotel Lahore", city: "Lahore", area: "Mall Road", image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80", stars: 4, rating: 8.8, reviewCount: 1900, price: 20000, originalPrice: 24000, badge: "Popular", badgeClass: "", amenities: ["WiFi", "Pool", "Restaurant", "Gym"] },
  { name: "Faletti's Hotel", city: "Lahore", area: "Egerton Road", image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80", stars: 4, rating: 8.6, reviewCount: 1560, price: 15000, originalPrice: 18000, badge: "Heritage", badgeClass: "", amenities: ["WiFi", "Restaurant", "Historic Building", "Parking"] },
  { name: "Hotel One Lahore", city: "Lahore", area: "Gulberg", image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", stars: 3, rating: 8.2, reviewCount: 1100, price: 7000, originalPrice: 9000, badge: "Value", badgeClass: "", amenities: ["WiFi", "Restaurant", "Parking"] },
  { name: "Lahore Backpackers", city: "Lahore", area: "Mall Road", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80", stars: 1, rating: 7.8, reviewCount: 650, price: 2000, originalPrice: 0, badge: "Budget", badgeClass: "", amenities: ["WiFi", "Common Room"] },

  // ── KARACHI ──
  { name: "PC Hotel Karachi", city: "Karachi", area: "Club Road", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80", stars: 5, rating: 9.0, reviewCount: 3100, price: 38000, originalPrice: 45000, badge: "Top Luxury", badgeClass: "luxury", amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Gym", "Beach View"] },
  { name: "Movenpick Karachi", city: "Karachi", area: "Club Road", image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80", stars: 5, rating: 8.9, reviewCount: 2600, price: 40000, originalPrice: 46000, badge: "Popular", badgeClass: "", amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Gym"] },
  { name: "Ramada Karachi", city: "Karachi", area: "Airport", image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80", stars: 4, rating: 8.4, reviewCount: 1800, price: 16000, originalPrice: 20000, badge: "Business", badgeClass: "", amenities: ["WiFi", "Pool", "Restaurant", "Gym"] },
  { name: "Hotel Mehran", city: "Karachi", area: "Shahrah-e-Faisal", image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", stars: 3, rating: 8.0, reviewCount: 1300, price: 9000, originalPrice: 11000, badge: "Value", badgeClass: "", amenities: ["WiFi", "Restaurant", "Parking"] },
  { name: "Karachi Hostel", city: "Karachi", area: "Saddar", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80", stars: 1, rating: 7.6, reviewCount: 500, price: 2200, originalPrice: 0, badge: "Budget", badgeClass: "", amenities: ["WiFi", "Common Room", "Lockers"] },

  // ── HUNZA ──
  { name: "Serena Hunza", city: "Hunza", area: "Karimabad", image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80", stars: 4, rating: 9.4, reviewCount: 1400, price: 22000, originalPrice: 25000, badge: "Scenic", badgeClass: "luxury", amenities: ["WiFi", "Restaurant", "Mountain View", "Garden"] },
  { name: "Eagle Nest Hotel", city: "Hunza", area: "Duikar", image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", stars: 3, rating: 9.0, reviewCount: 1600, price: 12000, originalPrice: 15000, badge: "Views", badgeClass: "", amenities: ["WiFi", "Restaurant", "Panoramic View"] },
  { name: "Hunza Explorers Inn", city: "Hunza", area: "Aliabad", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80", stars: 2, rating: 8.4, reviewCount: 850, price: 5000, originalPrice: 7000, badge: "Value", badgeClass: "", amenities: ["WiFi", "Basic Meals", "Mountain View"] },
  { name: "Old Hunza Inn", city: "Hunza", area: "Karimabad", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80", stars: 1, rating: 8.2, reviewCount: 1200, price: 3000, originalPrice: 4000, badge: "Budget", badgeClass: "", amenities: ["WiFi", "Meals Included"] },
];

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri || mongoUri === "your_mongodb_atlas_uri_here") {
      console.error("❌ Please set a valid MONGO_URI in your .env file first!");
      console.log("   Sign up at https://www.mongodb.com/cloud/atlas");
      process.exit(1);
    }

    console.log("🔗 Connecting to MongoDB...");
    await mongoose.connect(mongoUri);
    console.log("✅ Connected to MongoDB");

    // Clear existing data
    console.log("🗑️  Clearing existing data...");
    await Destination.deleteMany({});
    await Hotel.deleteMany({});

    // Insert destinations
    console.log("🗺️  Seeding destinations...");
    const insertedDestinations = await Destination.insertMany(destinations);
    console.log(`   ✅ ${insertedDestinations.length} destinations inserted`);

    // Insert hotels
    console.log("🏨 Seeding hotels...");
    const insertedHotels = await Hotel.insertMany(hotels);
    console.log(`   ✅ ${insertedHotels.length} hotels inserted`);

    console.log("\n🎉 Database seeded successfully!");
    console.log(`   📍 ${insertedDestinations.length} destinations`);
    console.log(`   🏨 ${insertedHotels.length} hotels`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error.message);
    process.exit(1);
  }
};

seedDatabase();
